export const GET_BUSKER_DETAIL_SUCCESS = "GET_BUSKER_DETAIL_SUCCESS";
export const GET_BUSKER_DETAIL_REQUEST = "GET_BUSKER_DETAIL_REQUEST";
export const GET_BUSKER_TRAILS_SUCCESS = "GET_BUSKER_TRAILS_SUCCESS";
export const GET_BUSKER_TRAILS_REQUEST = "GET_BUSKER_TRAILS_REQUEST";
export const GET_BUSKER_MOMENTS_SUCCESS = "GET_BUSKER_MOMENTS_SUCCESS";
export const GET_BUSKER_MOMENTS_REQUEST = "GET_BUSKER_MOMENTS_REQUEST";
export const GET_BUSKER_ALBUMS_SUCCESS = "GET_BUSKER_ALBUMS_SUCCESS";
export const GET_BUSKER_ALBUMS_REQUEST = "GET_BUSKER_ALBUMS_REQUEST";