export const GET_PERSONAL_BUSKER_TRAIL_SUCCESS = "GET_PERSONAL_BUSKER_TRAIL_SUCCESS";
export const GET_PERSONAL_BUSKER_TRAIL_REQUEST = "GET_PERSONAL_BUSKER_TRAIL_REQUEST";
export const DELETE_BUSKER_TRAIL = "DELETE_BUSKER_MOMENT";