export const GET_BUSKER_LIST = "busker/get_busker_list";
export const CHANGE_BUSKER_PAGE = "CHANGE_BUSKER_PAGE";
export const SORT_BUSKER_BY_AGE = "SORT_BUSKER_BY_AGE";
export const SORT_BUSKER_BY_TENDENCY = "SORT_BUSKER_BY_TENDENCY";
export const SEARCH_BUSKER = "SEARCH_BUSKER";
export const SET_RECOMMEND_BUSKER = "SET_RECOMMEND_BUSKER";