export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_COMMENTS_SUCCESS = "GET_ALBUM_COMMENTS_SUCCESS";
export const GET_ALBUM_COMMENTS_REQUEST = "GET_ALBUM_COMMENTS_REQUEST";
export const GET_ALBUM_SINGLES_SUCCESS = "GET_ALBUM_SINGLES_SUCCESS";
export const GET_ALBUM_SINGLES_REQUEST = "GET_ALBUM_SINGLES_REQUEST";
export const ADD_ALBUM_COMMENT = "ADD_ALBUM_COMMENT";