export const GET_PERSONAL_BUSKER_MOMENT_SUCCESS = "GET_PERSONAL_BUSKER_MOMENT_SUCCESS";
export const GET_PERSONAL_BUSKER_MOMENT_REQUEST = "GET_PERSONAL_BUSKER_MOMENT_REQUEST";
export const DELETE_BUSKER_MOMENT = "DELETE_BUSKER_MOMENT";